-- Seed data will be added here after user creation through Supabase Auth
-- Example:
/*
insert into public.users (id, email, full_name, company_name, company_role)
values 
  ('00000000-0000-0000-0000-000000000000', 'test@example.com', 'Test User', 'Test Company', 'Manager');
*/ 

-- INDUSTRY TAGS
insert into public.tags (type, value) values
('industry', 'Aerospace & Aviation'),
('industry', 'Agriculture'),
('industry', 'Automotive'),
('industry', 'Biotech'),
('industry', 'Construction'),
('industry', 'Consumer Goods'),
('industry', 'Defence'),
('industry', 'Education'),
('industry', 'Electronics'),
('industry', 'Energy & Utilities'),
('industry', 'Entertainment'),
('industry', 'Environmental Services'),
('industry', 'Financial Services'),
('industry', 'Food & Beverage'),
('industry', 'Forestry'),
('industry', 'Government'),
('industry', 'Healthcare'),
('industry', 'Hospitality'),
('industry', 'IT & Software'),
('industry', 'Legal'),
('industry', 'Logistics & Transport'),
('industry', 'Manufacturing'),
('industry', 'Marine & Shipbuilding'),
('industry', 'Media'),
('industry', 'Mining & Resources'),
('industry', 'Nonprofit'),
('industry', 'Oil & Gas'),
('industry', 'Pharmaceuticals'),
('industry', 'Real Estate'),
('industry', 'Retail'),
('industry', 'Telecommunications'),
('industry', 'Textiles'),
('industry', 'Tourism');

-- CAPABILITY TAGS
insert into public.tags (type, value) values
('capability', '3D Printing'),
('capability', 'Assembly'),
('capability', 'Automation'),
('capability', 'CNC Machining'),
('capability', 'CAD Design'),
('capability', 'CAM Programming'),
('capability', 'Casting'),
('capability', 'Chemical Processing'),
('capability', 'Cleanroom Manufacturing'),
('capability', 'Coating & Finishing'),
('capability', 'Composites'),
('capability', 'Consulting'),
('capability', 'Cutting'),
('capability', 'Die Making'),
('capability', 'Distribution'),
('capability', 'Drilling'),
('capability', 'E-Commerce Integration'),
('capability', 'Electronics Assembly'),
('capability', 'Engineering Services'),
('capability', 'ERP Integration'),
('capability', 'Fabrication'),
('capability', 'Fulfillment'),
('capability', 'Import/Export'),
('capability', 'Injection Molding'),
('capability', 'Inspection & QA'),
('capability', 'IoT Integration'),
('capability', 'IT Services'),
('capability', 'Laser Cutting'),
('capability', 'Logistics'),
('capability', 'Maintenance'),
('capability', 'Manufacturing'),
('capability', 'Marketing'),
('capability', 'Metal Forming'),
('capability', 'Milling'),
('capability', 'Packaging'),
('capability', 'Painting'),
('capability', 'Plastics'),
('capability', 'Printing'),
('capability', 'Procurement'),
('capability', 'Product Design'),
('capability', 'Prototyping'),
('capability', 'Software Development'),
('capability', 'Supply Chain Consulting'),
('capability', 'Welding');

-- REGION TAGS (Provinces)
insert into public.tags (type, value) values
('region', 'Alberta'),
('region', 'British Columbia'),
('region', 'Manitoba'),
('region', 'New Brunswick'),
('region', 'Newfoundland and Labrador'),
('region', 'Nova Scotia'),
('region', 'Ontario'),
('region', 'Prince Edward Island'),
('region', 'Quebec'),
('region', 'Saskatchewan'),
('region', 'Northwest Territories'),
('region', 'Nunavut'),
('region', 'Yukon');

-- REGION TAGS (Major Cities & Metros)
insert into public.tags (type, value) values
('region', 'Toronto'),
('region', 'Vancouver'),
('region', 'Montreal'),
('region', 'Ottawa'),
('region', 'Calgary'),
('region', 'Edmonton'),
('region', 'Winnipeg'),
('region', 'Hamilton'),
('region', 'Quebec City'),
('region', 'Kitchener–Waterloo'),
('region', 'Halifax'),
('region', 'London'),
('region', 'Victoria'),
('region', 'Windsor'),
('region', 'Saskatoon'),
('region', 'Regina'),
('region', 'St. John''s'),
('region', 'Charlottetown'),
('region', 'Whitehorse'),
('region', 'Yellowknife'); 